import type { Report } from "@/types";

const createTimestamp = (): { toDate: () => Date } => ({
  toDate: () => new Date(),
});

export const mockReports: Report[] = [
  {
    id: "1",
    title: "Bache peligroso en Av. Corrientes",
    description: "Hay un bache muy grande cerca del cruce con Callao que es un peligro para los autos y motos.",
    category: "baches",
    location: { latitude: -34.6037, longitude: -58.3816 },
    address: "Av. Corrientes 1234, CABA",
    coordinates: { lat: -34.6037, lng: -58.3816 },
    images: ["https://placehold.co/600x400.png?text=Bache+1", "https://placehold.co/600x400.png?text=Bache+2"],
    status: "pending",
    priority: "high",
    isPublic: true,
    userId: "user1",
    municipalityId: "caba",
    upvotes: 15,
    upvotedBy: [],
    tags: ["calle", "peligro"],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "2",
    title: "Luz quemada en poste de Plaza Serrano",
    description: "El farol de la esquina de Honduras y Serrano no funciona desde hace una semana.",
    category: "alumbrado",
    location: { latitude: -34.588, longitude: -58.427 },
    address: "Honduras 5000, CABA",
    coordinates: { lat: -34.588, lng: -58.427 },
    images: ["https://placehold.co/600x400.png?text=Luz+Quemada"],
    status: "in_progress",
    priority: "medium",
    isPublic: true,
    userId: "user2",
    municipalityId: "caba",
    upvotes: 7,
    upvotedBy: [],
    tags: ["iluminacion", "plaza"],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "3",
    title: "Basura acumulada en contenedor",
    description: "El contenedor de la esquina está desbordado de basura, necesita recolección urgente.",
    category: "basura",
    location: { latitude: -34.6178, longitude: -58.3686 },
    address: "Av. de Mayo 500, CABA",
    coordinates: { lat: -34.6178, lng: -58.3686 },
    images: [],
    status: "resolved",
    priority: "urgent",
    isPublic: true,
    userId: "user3",
    municipalityId: "caba",
    upvotes: 22,
    upvotedBy: [],
    tags: ["limpieza", "contenedor"],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
    resolvedAt: createTimestamp(),
  },
  {
    id: "4",
    title: "Señal de PARE caída",
    description: "La señal de PARE en la esquina de Defensa y Chile se cayó y puede causar un accidente.",
    category: "senalizacion",
    location: { latitude: -34.6173, longitude: -58.3725 },
    address: "Defensa 800, San Telmo",
    coordinates: { lat: -34.6173, lng: -58.3725 },
    images: ["https://placehold.co/600x400.png?text=Señal+Caída"],
    status: "pending",
    priority: "high",
    isPublic: true,
    userId: "user1",
    municipalityId: "caba",
    upvotes: 11,
    upvotedBy: [],
    tags: ["transito", "seguridad"],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
  {
    id: "5",
    title: "Banco roto en Parque Lezama",
    description: "Uno de los bancos de madera cerca del anfiteatro está roto.",
    category: "espacios_verdes",
    location: { latitude: -34.6276, longitude: -58.3699 },
    address: "Parque Lezama, CABA",
    coordinates: { lat: -34.6276, lng: -58.3699 },
    images: ["https://placehold.co/600x400.png?text=Banco+Roto"],
    status: "rejected",
    priority: "low",
    isPublic: false,
    userId: "user2",
    municipalityId: "caba",
    upvotes: 3,
    upvotedBy: [],
    tags: ["parque", "mobiliario"],
    createdAt: createTimestamp(),
    updatedAt: createTimestamp(),
  },
];
